# Generated by Django 5.2.4 on 2025-07-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='data',
        ),
        migrations.AddField(
            model_name='log',
            name='event',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
