# Generated by Django 5.2.4 on 2025-07-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0002_remove_log_data_log_event_alter_log_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
