# Generated by Django 5.2.4 on 2025-07-07 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0005_alter_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
