# Generated by Django 5.2.4 on 2025-07-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0007_alter_log_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='event',
        ),
        migrations.AddField(
            model_name='log',
            name='esp_id',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='log',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
    ]
