# Generated by Django 5.2.4 on 2025-07-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0008_remove_log_event_log_esp_id_log_humidity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='date',
        ),
        migrations.RemoveField(
            model_name='log',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='log',
            name='temperature',
        ),
        migrations.AddField(
            model_name='log',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
