# Generated by Django 5.2.4 on 2025-07-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0010_log_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='date',
            new_name='timestamp',
        ),
    ]
