# Generated by Django 5.2.4 on 2025-07-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0011_rename_date_log_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='area',
            field=models.IntegerField(default=0),
        ),
    ]
