# Generated by Django 5.2 on 2025-09-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0012_log_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='area',
        ),
    ]
