# Generated by Django 5.2 on 2025-09-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('coords', models.JSONField(default={})),
                ('label', models.CharField(default='Lamce COPPE/UFRJ', max_length=50)),
                ('value', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
