# Generated by Django 5.2 on 2025-09-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='coords',
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
