# Generated by Django 5.2.4 on 2025-07-21 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('variables', models.JSONField(default={})),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('esp_id', models.CharField(default='', max_length=12)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
