# Generated by Django 5.2.4 on 2025-07-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='master',
            field=models.BooleanField(default=False),
        ),
    ]
