# Generated by Django 5.2 on 2025-09-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0002_device_area_device_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='node',
            field=models.CharField(default='', max_length=50),
        ),
    ]
