# Generated by Django 5.2 on 2025-09-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('area', models.IntegerField(default=0)),
                ('label', models.CharField(default='GRVA', max_length=30)),
            ],
        ),
    ]
