# Generated by Django 5.2 on 2025-09-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Areas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area',
            new_name='value',
        ),
    ]
